config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root "home#index"
  
  resources :books
  resources :clients
  resources :librarians
  resources :authors
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy

    validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reservations, dependent: :destroy

  validates :author_id, :name, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :reservations, dependent: :destroy

    validates :name, presence: true
end

app/models/librarian.rb
class Librarian < ApplicationRecord
    has_many :reservations, dependent: :destroy

    validates :name, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :client
  belongs_to :book
  belongs_to :librarian
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def index

    end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :set_author, only: [:edit, :show, :update, :destroy]
    add_flash_types :red, :green, :yellow

    def index
        @authors = Author.all
    end

    def show
    end

    def new
        @author = Author.new
    end

    def create
        @author = Author.new(author_params)
        
        if @author.save
            redirect_to authors_path, green: ["Author criado com sucesso"]
        else
            redirect_to new_author_path, red: @author.errors.full_messages
        end
    end

    def edit
    end

    def update
        if @author.update(author_params)
            redirect_to authors_path, green: ["Author atualizado com sucesso"]
        else
            redirect_to edit_author_path(@author), red: @author.errors.full_messages
        end
    end

    def destroy
        @author.destroy
        redirect_to authors_path, green: ["Author apagado com sucesso"]
    end

    def set_author
        @author = Author.find(params[:id])
    end

    def author_params
        params.require(:author).permit(:name)
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:edit, :show, :update, :destroy]
    add_flash_types :red, :green, :yellow

    def index
        @books = Book.all
    end

    def show
    end

    def new
        @book = Book.new
        @authors = Author.all
    end

    def create
        @book = Book.new(book_params)
        
        if @book.save
            redirect_to books_path, green: ["Book criado com sucesso"]
        else
            redirect_to new_book_path, red: @book.errors.full_messages
        end
    end

    def edit
        @authors = Author.all
    end

    def update
        if @book.update(book_params)
            redirect_to books_path, green: ["Book atualizado com sucesso"]
        else
            redirect_to edit_book_path(@librarian), red: @librarian.errors.full_messages
        end
    end

    def destroy
        @book.destroy
        redirect_to books_path, green: ["Book apagado com sucesso"]
    end

    def set_book
        @book = Book.find(params[:id])
    end

    def book_params
        params.require(:book).permit(:name, :author_id)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :set_client, only: [:edit, :show, :update, :destroy]
    add_flash_types :red, :green, :yellow

    def index
        @clients = Client.all
    end

    def show
    end

    def new
        @client = Client.new
    end

    def create
        @client = Client.new(client_params)
        
        if @client.save()
            redirect_to clients_path, green: ["Book criado com sucesso"]
        else
            redirect_to new_client_path, red: @client.errors.full_messages
        end
    end

    def edit
    end

    def update
        if @client.update(client_params)
            redirect_to clients_path, green: ["Client atualizado com sucesso"]
        else
            redirect_to edit_client_path(@client), red: @client.errors.full_messages
        end
    end

    def destroy
        @client.destroy
        redirect_to clients_path, green: ["Client apagado com sucesso"]
    end

    def set_client
        @client = Client.find(params[:id])
    end

    def client_params
        params.require(:client).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
    before_action :set_librarian, only: [:edit, :show, :update, :destroy]
    add_flash_types :red, :green, :yellow

    def index
        @librarians = Librarian.all
    end

    def show
    end

    def new
        @librarian = Librarian.new
    end

    def create
        @librarian = Librarian.new(librarian_params)
        
        if @librarian.save
            redirect_to librarians_path, green: ["Librarian criado com sucesso"]
        else
            redirect_to new_librarian_path, red: @librarian.errors.full_messages
        end
    end

    def edit
    end

    def update
        if @librarian.update(librarian_params)
            redirect_to librarians_path, green: ["Librarian atualizado com sucesso"]
        else
            redirect_to edit_librarian_path(@librarian), red: @librarian.errors.full_messages
        end
    end

    def destroy
        @librarian.destroy
        redirect_to librarians_path, green: ["Librarian deletado com sucesso"]
    end

    def set_librarian
        @librarian = Librarian.find(params[:id])
    end

    def librarian_params
        params.require(:librarian).permit(:name)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :set_reservation, only: [:edit, :show, :update, :destroy]
    add_flash_types :red, :green, :yellow

    def index
        @reservations = Reservation.all
    end

    def show
    end

    def new
        @reservation = Reservation.new

        @books = Book.all
        @librarians = Librarian.all
        @clients = Client.all
    end

    def create
        @reservation = Reservation.new(reservation_params)
        
        if @reservation.save()
            redirect_to reservations_path, green: ["Reservation criado com sucesso"]
        else
            redirect_to new_reservation_path, red: @reservation.errors.full_messages
        end
    end

    def edit
        @books = Book.all
        @librarians = Librarian.all
        @clients = Client.all
    end

    def update
        if @reservation.update(reservation_params)
            redirect_to reservations_path, green: ["Reservation atualizado com sucesso"]
        else
            redirect_to edit_reservation_path(@reservation), red: @reservation.errors.full_messages
        end
    end

    def destroy
        @reservation.destroy
        redirect_to reservations_path, green: ["Reservation apagado com sucesso"]
    end

    def set_reservation
        @reservation = Reservation.find(params[:id])
    end

    def reservation_params
        params.require(:reservation).permit(:active, :client_id, :book_id, :librarian_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/authors/_form.html.erb
<%= form_with model: resource do |form| %>
    <%= render "layouts/flash_messages" %>

    <%= form.text_field :name %>

    <%= form.submit %>
<% end %>

<%= link_to "Back", authors_path %>

app/views/authors/edit.html.erb
<%= render partial: "authors/form", locals: {resource: @author}%>

app/views/authors/index.html.erb
<h3>Authors</h3>
<%= render "layouts/flash_messages" %>
<%= link_to "New Author", new_author_path %>
<br>
<% @authors.each do |author| %>
    Nome: <%= author.name %> |
    <%= link_to "Show", author_path(author) %>
    <%= link_to "Edit", edit_author_path(author) %>
    <%= link_to "Delete", author_path(author), method: :delete, data: {confirm: "Are you sure?"}%>
    <br>
<% end %>

app/views/authors/new.html.erb
<%= render partial: "authors/form", locals: {resource: @author}%>

app/views/authors/show.html.erb
Nome: <%= @author.name %><br>
<%= link_to "Back", authors_path %>

app/views/books/_form.html.erb
<%= form_with model: resource do |form| %>
    <%= render "layouts/flash_messages" %>

    <%= form.text_field :name %>

    <%= form.select :author_id, @authors.collect { |author| [author.name, author.id] }  %>

    <%= form.submit %>
<% end %>

<%= link_to "Back", books_path %>

app/views/books/edit.html.erb
<%= render partial: "books/form", locals: {resource: @book}%>

app/views/books/index.html.erb
<h3>Books</h3>
<%= render "layouts/flash_messages" %>
<%= link_to "New Book", new_book_path %>
<br>
<% @books.each do |book| %>
    Titulo: <%= book.name %> |
    Autor: <%= book.author.name %> |
    <%= link_to "Show", book_path(book) %>
    <%= link_to "Edit", edit_book_path(book) %>
    <%= link_to "Delete", book_path(book), method: :delete, data: {confirm: "Are you sure?"}%>
    <br>
<% end %>

app/views/books/new.html.erb
<%= render partial: "books/form", locals: {resource: @book}%>

app/views/books/show.html.erb
<%= @book.name %>
<%= @book.author.name %><br>
<%= link_to "Back", books_path %>

app/views/clients/_form.html.erb
<%= form_with model: resource do |form| %>
    <%= render "layouts/flash_messages" %>

    <%= form.text_field :name %>


    <%= form.submit %>
<% end %>

<%= link_to "Back", clients_path %>

app/views/clients/edit.html.erb
<%= render partial: "clients/form", locals: {resource: @client}%>

app/views/clients/index.html.erb
<h3>Clients</h3>
<%= render "layouts/flash_messages" %>
<%= link_to "New Client", new_client_path %>
<br>
<% @clients.each do |client| %>
    <%= client.name %>
    <%= link_to "Edit", edit_client_path(client) %>
    <%= link_to "Delete", client_path(client), method: :delete, data: {confirm: "Are you sure?"}%>
    <br>
<% end %>

app/views/clients/new.html.erb
<%= render partial: "clients/form", locals: {resource: @client}%>

app/views/clients/show.html.erb
Name: <%= client.name %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, errors| %>
    <div style= "color:<%= name %>">
        <% errors.each do |msg| %>
            <%= msg %>
        <% end %>
    </div>
<% end %>

app/views/layouts/_menu.html.erb
<h3>MENU</h3>
<%= link_to "Librarians", librarians_path %>
<%= link_to "Clients", clients_path %>
<%= link_to "Books", books_path %>
<%= link_to "Authors", authors_path %>
<%= link_to "Reservations", reservations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= render partial: "layouts/menu" %> 

  </body>
</html>

app/views/librarians/_form.html.erb
<%= form_with model: resource do |form| %>
    <%= render "layouts/flash_messages" %>

    <%= form.text_field :name %>

    <%= form.submit %>
<% end %>

<%= link_to "Back", librarians_path %>

app/views/librarians/edit.html.erb
<%= render partial: "librarians/form", locals: {resource: @librarian}%>

app/views/librarians/index.html.erb
<h3>Librarians</h3>
<%= render "layouts/flash_messages" %>
<%= link_to "New Librarian", new_librarian_path %>
<br>
<% @librarians.each do |librarian| %>
    Name: <%= librarian.name %>
    <%= link_to "Edit", edit_librarian_path(librarian) %>
    <%= link_to "Delete", librarian_path(librarian), method: :delete, data: {confirm: "Are you sure?"}%>
    <br>
<% end %>

app/views/librarians/new.html.erb
<%= render partial: "librarians/form", locals: {resource: @librarian}%>

app/views/librarians/show.html.erb
Name: <%= librarian.name %><br>
<%= link_to "Back", librarians_path %>

app/views/reservations/_form.html.erb
<%= form_with model: resource do |form| %>
    <%= render "layouts/flash_messages" %>

    Active: <%= form.check_box :active %><br>
    Book: <%= form.select :book_id, @books.collect { |book| [book.name, book.id] }  %><br>
    Client: <%= form.select :client_id, @clients.collect { |client| [client.name, client.id] }  %><br>
    Librarian: <%= form.select :librarian_id, @librarians.collect { |librarian| [librarian.name, librarian.id] }  %><br>


    <%= form.submit %>
<% end %>

<%= link_to "Back", reservations_path %>

app/views/reservations/edit.html.erb
<%= render partial: "reservations/form", locals: {resource: @reservation}%>

app/views/reservations/index.html.erb
<h3>Reservations</h3>
<%= render "layouts/flash_messages" %>
<%= link_to "New Reservation", new_reservation_path %>
<br>
<% @reservations.each do |reservation| %>
    Active : <%= reservation.active %>
    Client: <%= reservation.client.name %> |
    Book: <%= reservation.book.name %> |
    Librarian: <%= reservation.librarian.name %> |
    <%= link_to "Edit", edit_reservation_path(reservation) %>
    <%= link_to "Delete", reservation_path(reservation), method: :delete, data: {confirm: "Are you sure?"}%>
    <br>
<% end %>

app/views/reservations/new.html.erb
<%= render partial: "reservations/form", locals: {resource: @reservation}%>

app/views/reservations/show.html.erb
<%= author.name %>